"""add telegram_clients and issues

Revision ID: b4b29053ad3e
Revises: 221d96af3a9b
Create Date: 2026-06-19 16:38:17.262654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4b29053ad3e'
down_revision: Union[str, Sequence[str], None] = '221d96af3a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('issue_type', sa.Enum('COMPUTER', 'NETWORK', 'PRINTER', name='issuetype'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'RESOLVED', name='issuestatus'), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_clients',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('telegram_username', sa.String(), nullable=True),
    sa.Column('telegram_first_name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_clients')
    op.drop_table('issues')
    # ### end Alembic commands ###
